name: Audit

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install Clippy
        run: rustup component add clippy

      - name: Run Clippy - Verificando qualidade do código, práticas recomendadas, e possíveis bug
        run: cargo clippy -- -D warnings

      - name: Install Rustfmt
        run: rustup component add rustfmt

      - name: Check Rustfmt - Verificando formatação do código
        run: cargo fmt -- --check

      - name: Install cargo-deny
        run: cargo install cargo-deny

      - name: Run cargo-deny - Verificando se possui algum pacote com vulnerabilidade, licenciamento e políticas de dependências
        run: cargo deny check

      - name: Install MIRAI
        run: cargo install mirai

      - name: Run MIRAI - Verificando possíveis falhas de segurança em tempo de compilação
        run: cargo mirai
